# Generated by Django 5.0.6 on 2024-06-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSubscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
